# Generated by Django 5.0.1 on 2024-01-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ytdata',
            old_name='description',
            new_name='summarized',
        ),
        migrations.AddField(
            model_name='ytdata',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
